FROM registry.fedoraproject.org/fedora-toolbox:latest

LABEL name="dev-toolbox"

RUN sudo dnf copr enable -y atim/starship && \
  sudo dnf copr enable -y jdxcode/mise && \
  sudo dnf install -y \
  starship \
  neovim \
  tmux \
  mise \
  && \
  sudo dnf clean all
