FROM registry.fedoraproject.org/fedora-toolbox:latest

RUN dnf update -y && \
  dnf copr enable -y atim/starship && \
  dnf copr enable -y jdxcode/mise && \
  dnf install -y \
  pinentry \
  starship \
  fd-find \
  neovim \
  tmux \
  mise \
  zsh && \
  dnf clean all

