#!/bin/bash

set -e

# Get absolute paths. Symlinks require absolute paths to work reliably from anywhere.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Resolves to the absolute path of your config folder (e.g., /home/user/.local/dot-files/config)
SOURCE_CONFIG_DIR="$(realpath "$SCRIPT_DIR/../../config")"

# ========== Utility Functions ==========

function backup_and_link() {
  local SOURCE_PATH="$1"
  local TARGET_PATH="$2"

  # Check if source exists before doing anything
  if [ ! -e "$SOURCE_PATH" ]; then
    echo "Error: Source config not found at $SOURCE_PATH"
    return 1
  fi

  # Create parent directory for target if it doesn't exist
  local TARGET_DIR
  TARGET_DIR=$(dirname "$TARGET_PATH")
  mkdir -p "$TARGET_DIR"

  # Handle existing configuration at target
  if [ -e "$TARGET_PATH" ] || [ -L "$TARGET_PATH" ]; then
    # If it's already a symlink pointing to the correct place, skip
    local CURRENT_LINK
    if [ -L "$TARGET_PATH" ]; then
      CURRENT_LINK=$(readlink -f "$TARGET_PATH")
      if [ "$CURRENT_LINK" == "$SOURCE_PATH" ]; then
        echo "Link already correct for $(basename "$TARGET_PATH"). Skipping."
        return 0
      fi
    fi

    echo -e "\nConfiguration at $TARGET_PATH exists. Backing up..."

    if [ -e "$TARGET_PATH.bak" ]; then
      echo "Removing old backup..."
      rm -rf "$TARGET_PATH.bak"
    fi

    mv "$TARGET_PATH" "$TARGET_PATH.bak"
    echo "Backup moved to $TARGET_PATH.bak"
  fi

  # Create the symlink
  echo "Linking $SOURCE_PATH -> $TARGET_PATH"
  ln -s "$SOURCE_PATH" "$TARGET_PATH"
}

# ========== GTK Theme ==========

echo -e "\n--- Setting GTK Theme ---"
gsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
echo "GTK theme set."

# ========== Solaar ==========

echo -e "\n--- Configuring Solaar ---"

SOLAAR_SOURCE="$SOURCE_CONFIG_DIR/solaar"
SOLAAR_TARGET="$HOME/.var/app/io.github.pwr_solaar.solaar/config/solaar"

# Link the entire folder
backup_and_link "$SOLAAR_SOURCE" "$SOLAAR_TARGET"

# Handle udev rules (Copy is safer here as /etc is owned by root/system)
echo "Installing udev rules..."
find "$SOLAAR_SOURCE" -name "*.rules" -exec sudo cp {} /etc/udev/rules.d/ \;
sudo udevadm control --reload-rules

# ========== Neovim ==========

echo -e "\n--- Configuring Neovim ---"

NEOVIM_SOURCE="$SOURCE_CONFIG_DIR/nvim"
# Flatpak path
NEOVIM_TARGET="$HOME/.config/nvim"

backup_and_link "$NEOVIM_SOURCE" "$NEOVIM_TARGET"

# ========== Starship ==========

echo -e "\n--- Configuring Starship ---"

STARSHIP_SOURCE="$SOURCE_CONFIG_DIR/starship.toml"
STARSHIP_TARGET="$HOME/.config/starship.toml"

backup_and_link "$STARSHIP_SOURCE" "$STARSHIP_TARGET"

# ========== tmux ==========

echo -e "\n--- Configuring tmux ---"

# Note: Linking the file directly instead of the folder allows you to have
# other unrelated files in ~/.config/tmux if generated by the system.
# To manage the whole folder, link the folder instead.
TMUX_SOURCE_FILE="$SOURCE_CONFIG_DIR/tmux/tmux.conf"
TMUX_TARGET_FILE="$HOME/.config/tmux/tmux.conf"

backup_and_link "$TMUX_SOURCE_FILE" "$TMUX_TARGET_FILE"

# ========== Zsh ==========

echo -e "\n--- Configuring Zsh ---"

ZSH_SOURCE_FILE="$(realpath "$SOURCE_CONFIG_DIR/zsh/zshrc")"
ZSH_TARGET_FILE="$HOME/.zshrc"
ZSH_SOURCE_DIR="$(realpath "$SOURCE_CONFIG_DIR/zsh/zshrc.d")"
ZSH_TARGET_DIR="$HOME/.zshrc.d"

backup_and_link "$ZSH_SOURCE_FILE" "$ZSH_TARGET_FILE"
backup_and_link "$ZSH_SOURCE_DIR" "$ZSH_TARGET_DIR"

echo -e "\nAll configurations linked successfully.\n"
