[tools]
bun = "latest"
fd = "latest"
glow = "latest"
go = "latest"
golangci-lint = "latest"
lua-language-server = "latest"
neovim = "nightly"
node = "lts"
ripgrep = "latest"
ruff = "latest"
shfmt = "latest"
stylua = "latest"
tree-sitter = "latest"
usage = "latest"
"aqua:quarylabs/sqruff" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"
eza = "latest"
opencode = "latest"
"go:golang.org/x/tools/gopls" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
