[tools]
bun = "latest"
fd = "latest"
glow = "latest"
go = "latest"
golangci-lint = "latest"
lua-language-server = "latest"
neovim = "nightly"
node = "24.14.0"
ripgrep = "latest"
ruff = "latest"
shfmt = "latest"
stylua = "latest"
tree-sitter = "latest"
usage = "latest"
"aqua:quarylabs/sqruff" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:typescript-language-server" = "latest"
"npm:typescript" = "latest"
eza = "latest"
opencode = "latest"
